"""add mvp core models

Revision ID: 61108f8dfb03
Revises: 0001_bootstrap
Create Date: 2026-02-24 00:45:46.892450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61108f8dfb03'
down_revision: Union[str, Sequence[str], None] = '0001_bootstrap'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skill_stack', sa.Text(), nullable=True),
    sa.Column('interest_energy_curve', sa.Text(), nullable=True),
    sa.Column('cognitive_style', sa.Text(), nullable=True),
    sa.Column('value_boundary', sa.Text(), nullable=True),
    sa.Column('risk_tolerance', sa.Text(), nullable=True),
    sa.Column('time_commitment', sa.Text(), nullable=True),
    sa.Column('raw_responses', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('diagnostic_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('content_pillars', sa.Text(), nullable=False),
    sa.Column('tone_style', sa.Text(), nullable=False),
    sa.Column('viewpoint_library', sa.Text(), nullable=False),
    sa.Column('differentiation', sa.Text(), nullable=False),
    sa.Column('growth_path', sa.Text(), nullable=False),
    sa.Column('monetization_path', sa.Text(), nullable=False),
    sa.Column('risk_boundary', sa.Text(), nullable=False),
    sa.Column('is_selected_primary', sa.Boolean(), nullable=False),
    sa.Column('is_selected_backup', sa.Boolean(), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_constitutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_model_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tone_words_used', sa.Text(), nullable=False),
    sa.Column('tone_words_forbidden', sa.Text(), nullable=False),
    sa.Column('tone_sentence_patterns', sa.Text(), nullable=False),
    sa.Column('viewpoint_fortress', sa.Text(), nullable=False),
    sa.Column('narrative_mainline', sa.Text(), nullable=False),
    sa.Column('growth_arc', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identity_model_id'], ['identity_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('launch_kits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_model_id', sa.String(length=36), nullable=False),
    sa.Column('persona_constitution_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('day_1_theme', sa.String(length=255), nullable=False),
    sa.Column('day_1_content', sa.Text(), nullable=False),
    sa.Column('day_2_theme', sa.String(length=255), nullable=False),
    sa.Column('day_2_content', sa.Text(), nullable=False),
    sa.Column('day_3_theme', sa.String(length=255), nullable=False),
    sa.Column('day_3_content', sa.Text(), nullable=False),
    sa.Column('day_4_theme', sa.String(length=255), nullable=False),
    sa.Column('day_4_content', sa.Text(), nullable=False),
    sa.Column('day_5_theme', sa.String(length=255), nullable=False),
    sa.Column('day_5_content', sa.Text(), nullable=False),
    sa.Column('day_6_theme', sa.String(length=255), nullable=False),
    sa.Column('day_6_content', sa.Text(), nullable=False),
    sa.Column('day_7_theme', sa.String(length=255), nullable=False),
    sa.Column('day_7_content', sa.Text(), nullable=False),
    sa.Column('sustainable_columns', sa.Text(), nullable=False),
    sa.Column('growth_experiment', sa.Text(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_model_id'], ['identity_models.id'], ),
    sa.ForeignKeyConstraint(['persona_constitution_id'], ['persona_constitutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launch_kits')
    op.drop_table('persona_constitutions')
    op.drop_table('identity_models')
    op.drop_table('diagnostics')
    # ### end Alembic commands ###
